### ISSUE TITLE
我觉得是不是可以不用实例方法，而是用 module 的方法

### ISSUE THREAD

**Issue by ShallmentMo** [waditu/tushare-ruby#3]
我觉得是不是可以不用实例方法，而是用 module 的方法。好像这样
```
module Tushare
  module Stock
    module Fundamental
      extend self
     def get_stock_basics
     end
    end
  end
end

Tushare::Stock::Fundamental.get_stock_basics
```
因为好像创建实例没什么用处，但是具体我也不清楚这样是不是更好，会不会有其它功能需要用这种创建实例的设计更好，就开个 issue 来问一下吧。
另外 spec 测试好像也可以按文件夹来放

**Comment by RobotJiang** [comment]
1.不错的建议。当时考虑用类的原因是，很多模块都有类似 protected ,private 的方法，而 module 里面默认都是公共方法，然后查找了其他变相实现module method 私有的方案，感觉都不是很好。
2.  如果都用 module ,然后里面都用类方法，调用的层次感确实较好，用类的话，也便于测试和构建mock，不过目前如你所说，貌似还看不太出太大的意义。所以我觉得都可以，但是需要一次重构。
3. spce ，现在加入 fundamental 后，可以创建 stock 文件夹，然后下面分别放 trading_spec, fundamental_spec ，这也是可以的。

**Comment by ShallmentMo** [comment]
我看了一下， module 也是可以定义 private method 的吧
```
module A
  extend self # 让 A 的方法可以直接调用

  def public_method
    p 'publish_method'
    private_method
  end

  private

  def private_method
   p 'private_method'
  end
end

A.public_method
# A.private_method #直接调用会报错 private method `private_a' called for A:Module (NoMethodError)
# C.c
```
PS: check 的话没问题，另外我们最好遵循 rubycop 的代码规范，如果需要编辑器有插件可以提醒的

**Comment by RobotJiang** [comment]
@ShallmentMo 不是哦，我是说 include A 啊。这样在别处引用回有副作用。另外你是说哪里没有遵循代码规范吗？

**Comment by ShallmentMo** [comment]
```
module A
  extend self

  def public_method
    p 'publish_method'
    # private_method
  end

  private

  def private_method
   p 'private_method'
  end
end

class B
  include A
end

class C
  extend A
end

A.public_method
# A.private_method # raise private method `private_method' called for A:Module (NoMethodError)
# C.c
b = B.new
b.public_method
# b.private_method # raise private method `private_method' called for #<B:0x007f8fb28489f8> (NoMethodError)
C.public_method
#C.private_method # raise private method `private_method' called for C:Class (NoMethodError)

```
我试了一下，private 是可以起作用的吧。用 module 是不想别人去实例化，而且 `extend self` 很好用，所以我不想用 class，不过看你吧。

**Comment by RobotJiang** [comment]
我是说内部调用，我最初是不想  include 后，其他类还可以调用它的私有方法。而且module里面定义私有方法也很奇怪，module的设计就是为了混入后，让所有方法成为目标类的实例方法。然后定义了私有方法就比较奇怪。倒不是有其他特别的想法。为实现有人是这么做：

module Foo
  def self.included(base)
    base.instance_eval do
      def method_name
        # ...
      end
      private_class_method :method_name
    end
  end
end

不过，我觉得有点偏题了，你的建议本来也非常好。我重构一下代码。到时候，你check一下。

**Comment by ShallmentMo** [comment]
ok

**Comment by RobotJiang** [comment]
Hi, @ShallmentMo 我重构并提交了代码。你有空 pull 下来看一下.
@ShallmentMo 加这个QQ群： 398053309 ，方便交流。 
Thanks !

**Comment by ShallmentMo** [comment]
done good, thx
