### ISSUE TITLE
复权数据如何获取？

### ISSUE THREAD

**Issue by grasp** [waditu/tushare-ruby#31]
数据下载了，但是没有复权数据，分析就失去了意义，一直无解。
如果能够有复权数据 ，配合其他数据， 才可以做回归测试。

**Comment by jimmysoa** [comment]
很多接口应该还在添加中，python版提供了复权数据。

**Comment by jimmysoa** [comment]
@RobotJiang @ShallmentMo 正在完善ruby版的开发。

**Comment by ShallmentMo** [comment]
@jimmysoa @RobotJiang @grasp 应该是还没加上的，迟点会增加

**Comment by ShallmentMo** [comment]
已经增加了
